version: '3.6'


services:

  drone:
    container_name: drone
    image: drone/drone:2
    restart: unless-stopped
    environment:
      - DRONE_DATABASE_DRIVER=sqlite3
      - DRONE_DATABASE_DATASOURCE=/data/database.sqlite
      - DRONE_GITHUB_CLIENT_ID=80d1fbcce5d637951ca7
      - DRONE_GITHUB_CLIENT_SECRET=37c4facd7a19a258ca895d32ade826c8806f822d
      - DRONE_GIT_ALWAYS_AUTH=false
      - DRONE_RPC_SECRET=37c4facd7a19a258ca895d32ade826c8806f822d
      - DRONE_SERVER_PROTO=https
      - DRONE_SERVER_HOST=81de-113-161-84-89.ap.ngrok.io
      - DRONE_TLS_AUTOCERT=false
      - DRONE_USER_CREATE=congtusoma146
      - DRONE_LOGS_DEBUG=true
      - DRONE_LOGS_TEXT=true
    ports:
      - "8080:80"
    networks:
      - drone_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./drone:/data

  drone-runner:
    container_name: drone-runner
    image: drone/drone-runner-docker:1
    restart: unless-stopped
    depends_on:
      - drone
    environment:
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_HOST=drone:80
      - DRONE_RPC_SECRET=37c4facd7a19a258ca895d32ade826c8806f822d
      - DRONE_RUNNER_NAME="0eb1-113-161-84-89.ap.ngrok.io-runner"
      - DRONE_RUNNER_CAPACITY=1
      - DRONE_RUNNER_NETWORKS=drone_net
      - DRONE_DEBUG=true
      - DRONE_TRACE=false
    ports:
      - "3000:3000"
    networks:
      - drone_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  drone_net:
    name: drone_net
